### ISSUE TITLE
Augment the service manager to pick up specified files

### ISSUE THREAD

**Issue by a-roberts** [rhd-gitops-example/services#9] opened 2020-03-17 13:50 UTC
I've had a look through the code and readme and noticed https://github.com/rhd-gitops-example/services/blob/master/pkg/avancement/service_manager.go#L64

So I assume deployment.txt is just an example of what we're using atm as a PoC, where do we think this should do instead going forward? 

I'm thinking it should pickup whatever folks we'd like, perhaps specified via some args and/or a file, so discussion welcome

(nit: should the package be `advancement` not `avancement`?)

**Comment by bigkevmcd** [comment] 2020-03-17 14:08
I'm working on this (naming to be fixed) here

https://github.com/rhd-gitops-example/services/blob/switch-from-git/pkg/git/gitcmd/repository.go#L51-L74

And sorry, `avancement` is French for `promotion` :-)

**Comment by mnuttall** [comment] 2020-03-17 15:53
This is also a duplicate of #2.

**Closed by mnuttall** 2020-03-17 15:53 UTC
